"""empty message

Revision ID: 027156ad9d38
Revises: 4a3bbf0728d7
Create Date: 2017-04-01 18:21:22.771926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027156ad9d38'
down_revision = '4a3bbf0728d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_inventory',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('purchasedate', sa.Date(), nullable=True),
    sa.Column('expirydate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('Medical Inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Medical Inventory',
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('medication', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('purchasedate', sa.DATE(), nullable=True),
    sa.Column('expirydate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_table('medical_inventory')
    # ### end Alembic commands ###
