"""empty message

Revision ID: 0618f04dd179
Revises: c9845633954b
Create Date: 2017-04-26 17:16:58.219413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0618f04dd179'
down_revision = 'c9845633954b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cowgroup',
    sa.Column('cownumber', sa.Text(), nullable=True),
    sa.Column('groupnumber', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.Text(), nullable=True),
    sa.Column('groupdescription', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('groupnumber', 'ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cowgroup')
    # ### end Alembic commands ###
