"""empty message

Revision ID: 07a7c5571aa9
Revises: 75177862bc47
Create Date: 2017-02-03 16:59:18.134153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a7c5571aa9'
down_revision = '75177862bc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_animal',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_animal')
    # ### end Alembic commands ###
