"""empty message

Revision ID: 0e7edbae1b47
Revises: 
Create Date: 2017-03-06 02:23:08.670174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7edbae1b47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_animal',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('eartag', sa.Text(), nullable=True),
    sa.Column('eid', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('pasturenumber', sa.Text(), nullable=True),
    sa.Column('breed', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('trial', sa.Text(), nullable=True),
    sa.Column('herd', sa.Text(), nullable=True),
    sa.Column('animaltype', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pwdhash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('master_animal')
    # ### end Alembic commands ###
