"""empty message

Revision ID: 261acdbd3b6a
Revises: 3bfc7dabb207
Create Date: 2017-05-18 14:38:56.509750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261acdbd3b6a'
down_revision = '3bfc7dabb207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herd_change',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('cownumber', sa.Text(), nullable=True),
    sa.Column('eid', sa.Text(), nullable=True),
    sa.Column('groupnumber', sa.Integer(), nullable=True),
    sa.Column('eartag', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('herd_change')
    # ### end Alembic commands ###
