"""empty message

Revision ID: 38807cbf9f16
Revises: b6e72bb1bdca
Create Date: 2017-04-05 15:20:01.671361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38807cbf9f16'
down_revision = 'b6e72bb1bdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_inventory', sa.Column('brand', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_inventory', 'brand')
    # ### end Alembic commands ###
