"""empty message

Revision ID: 42c620edb2f9
Revises: eba4a7c0c5d7
Create Date: 2017-09-08 17:58:56.759176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c620edb2f9'
down_revision = 'eba4a7c0c5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_inventory_dic',
    sa.Column('drug', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('roa', sa.Text(), nullable=True),
    sa.Column('vialsize', sa.Float(), nullable=True),
    sa.Column('units', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('drug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drug_inventory_dic')
    # ### end Alembic commands ###
