"""empty message

Revision ID: 4a3bbf0728d7
Revises: 0e7edbae1b47
Create Date: 2017-03-21 00:20:36.019334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3bbf0728d7'
down_revision = '0e7edbae1b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Medical Inventory',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('purchasedate', sa.Date(), nullable=True),
    sa.Column('expirydate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Medical Inventory')
    # ### end Alembic commands ###
