"""empty message

Revision ID: 599be20af6b8
Revises: d5994fb62821
Create Date: 2017-11-13 16:46:52.301070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599be20af6b8'
down_revision = 'd5994fb62821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herdchange',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cownumber', 'ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('herdchange')
    # ### end Alembic commands ###
