"""empty message

Revision ID: 75177862bc47
Revises: a32e4e805c75
Create Date: 2017-02-03 16:30:14.742944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75177862bc47'
down_revision = 'a32e4e805c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.Column('lastname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('pwdhash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
