"""empty message

Revision ID: 7dc7a2724906
Revises: e468adb7e6e4
Create Date: 2017-04-11 15:36:48.882650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc7a2724906'
down_revision = 'e468adb7e6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grazing',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('pastureacres', sa.Text(), nullable=True),
    sa.Column('animalspresent', sa.Text(), nullable=True),
    sa.Column('datein', sa.Text(), nullable=True),
    sa.Column('dateout', sa.Text(), nullable=True),
    sa.Column('stockingrate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('medical',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('reasonforprocedure', sa.Text(), nullable=True),
    sa.Column('notificationofvmo', sa.Text(), nullable=True),
    sa.Column('recommendationofvmo', sa.Text(), nullable=True),
    sa.Column('treatmentprotocol', sa.Text(), nullable=True),
    sa.Column('animallocationpreresolution', sa.Text(), nullable=True),
    sa.Column('followupexam', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('dateoffollowup', sa.Text(), nullable=True),
    sa.Column('animallocation', sa.Text(), nullable=True),
    sa.Column('dateofaction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical')
    op.drop_table('grazing')
    # ### end Alembic commands ###
