"""empty message

Revision ID: 8226aecd7776
Revises: 
Create Date: 2017-02-19 00:56:19.580586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8226aecd7776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_animal',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.drop_table('test1')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('test1',
    sa.Column('one', sa.VARCHAR(length=10), nullable=True),
    sa.Column('two', sa.SMALLINT(), nullable=True)
    )
    op.drop_table('master_animal')
    # ### end Alembic commands ###
