"""empty message

Revision ID: 8622a57e5803
Revises: 
Create Date: 2017-02-03 16:00:05.537674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8622a57e5803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reproduction')
    op.drop_table('users')
    op.drop_table('iacuc')
    op.drop_table('grazing')
    op.drop_table('master_animal')
    op.drop_table('experiment')
    op.drop_table('medical')
    op.drop_table('inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('trial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('herd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eartag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brandlocation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tattooleft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tattooright', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('altid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('breed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hornstatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dam', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sire', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateacquired', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('howacquired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datedisposed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('howdisposed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disposalreason', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('medical',
    sa.Column('dateofaction', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('trial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('herd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reasonforprocedure', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notificationofvmo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendationofvmo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('treatmentprotocol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animallocationpre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followupexam', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dateoffollowup', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animallocationpost', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('experiment',
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dam', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sire', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sireframescore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('damframescore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('birthweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weandate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('weanweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weanheight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adj205dweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adj205dheight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weanframescore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ageatwean', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yearlingdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('yearlingweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yearlingheight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjyearlingweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adjyearlingheight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ageatyearling', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yearlingframescore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customweightdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('customheight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('customheightdate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('backfat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('treatment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blockpen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('replicate', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('master_animal',
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eartag', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('eid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animaltype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('breed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('height', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('herd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('framescore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('grazing',
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('herd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pasturenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pastureacres', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('animalpresent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('datein', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dateout', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('stockingrate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('iacuc',
    sa.Column('pasturenumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dateinspectedpasture', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('generalappearancepasture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('livestock', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('animalcondition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fencing', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accesstofeed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accesstowater', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cleanlinessofwater', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accesstoshade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commentspasture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('majordefpasture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('minordefpasture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('buildingnumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dateinspectedbuilding', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('generalappearancebuilding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('electrical', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('housekeeping', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conditionofchute', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('penconditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidenceofslip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidenceofsharp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drugstorage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('commentsbuilding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('majordefbuilding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('minordefbuilding', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('users',
    sa.Column('uid', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pwdhash', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('reproduction',
    sa.Column('cowname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cownumber', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('herd', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('breeding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pregnancy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('calfatside', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('totalcalves', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('previouscow', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currentcalf', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('calfsex', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthweight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dam_calvingdisposition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('udderscore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('calvingease', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dam_ageatbirth', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
