"""empty message

Revision ID: 8819bca2082e
Revises: 42c620edb2f9
Create Date: 2017-09-14 15:54:29.251374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8819bca2082e'
down_revision = '42c620edb2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('cownumber', sa.Text(), nullable=True),
    sa.Column('eid', sa.Text(), nullable=True),
    sa.Column('groupnumber', sa.Integer(), nullable=True),
    sa.Column('eartag', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('users', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
