"""empty message

Revision ID: 99ceb76e7573
Revises: 38807cbf9f16
Create Date: 2017-04-05 15:21:27.571204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ceb76e7573'
down_revision = '38807cbf9f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_inventory',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('brandlocation', sa.Text(), nullable=True),
    sa.Column('tattooleft', sa.Text(), nullable=True),
    sa.Column('tattooright', sa.Text(), nullable=True),
    sa.Column('alternativeid', sa.Text(), nullable=True),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('dam', sa.Text(), nullable=True),
    sa.Column('hornstatus', sa.Text(), nullable=True),
    sa.Column('sire', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('howacquired', sa.Text(), nullable=True),
    sa.Column('dateacquired', sa.Text(), nullable=True),
    sa.Column('howdisposed', sa.Text(), nullable=True),
    sa.Column('datedisposed', sa.Text(), nullable=True),
    sa.Column('disposalreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_inventory')
    # ### end Alembic commands ###
