"""empty message

Revision ID: ad009160f20c
Revises: 027156ad9d38
Create Date: 2017-04-01 18:40:40.146703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad009160f20c'
down_revision = '027156ad9d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_inventory',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('medication', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('purchasedate', sa.Text(), nullable=True),
    sa.Column('expirydate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_inventory')
    # ### end Alembic commands ###
