"""empty message

Revision ID: af29e47b3843
Revises: ff4722933ece
Create Date: 2017-04-07 15:44:38.057038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af29e47b3843'
down_revision = 'ff4722933ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('dam', sa.Text(), nullable=True),
    sa.Column('sire', sa.Text(), nullable=True),
    sa.Column('birthweight', sa.Text(), nullable=True),
    sa.Column('damframescore', sa.Float(), nullable=True),
    sa.Column('sireframescore', sa.Float(), nullable=True),
    sa.Column('weanheight', sa.Float(), nullable=True),
    sa.Column('weanweight', sa.Float(), nullable=True),
    sa.Column('weandate', sa.Text(), nullable=True),
    sa.Column('adj205w', sa.Float(), nullable=True),
    sa.Column('adj205h', sa.Float(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('weanframescore', sa.Float(), nullable=True),
    sa.Column('ageatwean', sa.Float(), nullable=True),
    sa.Column('yearlingweight', sa.Float(), nullable=True),
    sa.Column('yearlingheight', sa.Float(), nullable=True),
    sa.Column('yearlingdate', sa.Text(), nullable=True),
    sa.Column('adjyearlingw', sa.Float(), nullable=True),
    sa.Column('adjyearlingh', sa.Float(), nullable=True),
    sa.Column('yearlingframescore', sa.Float(), nullable=True),
    sa.Column('ageatyearling', sa.Float(), nullable=True),
    sa.Column('customweight', sa.Float(), nullable=True),
    sa.Column('customweightdate', sa.Text(), nullable=True),
    sa.Column('customheight', sa.Float(), nullable=True),
    sa.Column('customheightdate', sa.Text(), nullable=True),
    sa.Column('backfat', sa.Float(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('blockpen', sa.Text(), nullable=True),
    sa.Column('replicate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment')
    # ### end Alembic commands ###
