"""empty message

Revision ID: b6e72bb1bdca
Revises: ad009160f20c
Create Date: 2017-04-03 16:56:36.128771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e72bb1bdca'
down_revision = 'ad009160f20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_inventory',
    sa.Column('cownumber', sa.Text(), nullable=False),
    sa.Column('brandlocation', sa.Text(), nullable=True),
    sa.Column('tattooleft', sa.Text(), nullable=True),
    sa.Column('tattooright', sa.Text(), nullable=True),
    sa.Column('alternativeid', sa.Text(), nullable=True),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('dam', sa.Text(), nullable=True),
    sa.Column('hornstatus', sa.Text(), nullable=True),
    sa.Column('sire', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('howacquired', sa.Text(), nullable=True),
    sa.Column('dateacquired', sa.Text(), nullable=True),
    sa.Column('howdisposed', sa.Text(), nullable=True),
    sa.Column('datedisposed', sa.Text(), nullable=True),
    sa.Column('disposalreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_inventory')
    # ### end Alembic commands ###
