"""empty message

Revision ID: c9845633954b
Revises: e0500522c895
Create Date: 2017-04-26 17:14:57.023739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9845633954b'
down_revision = 'e0500522c895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('cownumber', sa.Text(), nullable=True),
    sa.Column('groupnumber', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.Text(), nullable=True),
    sa.Column('groupdescription', sa.Text(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('groupnumber', 'ts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
