"""empty message

Revision ID: e468adb7e6e4
Revises: 
Create Date: 2017-04-10 18:29:26.169663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e468adb7e6e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test1',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('animal_inventory',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('brandlocation', sa.Text(), nullable=True),
    sa.Column('tattooleft', sa.Text(), nullable=True),
    sa.Column('tattooright', sa.Text(), nullable=True),
    sa.Column('alternativeid', sa.Text(), nullable=True),
    sa.Column('registration', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('dam', sa.Text(), nullable=True),
    sa.Column('hornstatus', sa.Text(), nullable=True),
    sa.Column('sire', sa.Text(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('howacquired', sa.Text(), nullable=True),
    sa.Column('dateacquired', sa.Text(), nullable=True),
    sa.Column('howdisposed', sa.Text(), nullable=True),
    sa.Column('datedisposed', sa.Text(), nullable=True),
    sa.Column('disposalreason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('experiment',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('dam', sa.Text(), nullable=True),
    sa.Column('sire', sa.Text(), nullable=True),
    sa.Column('birthweight', sa.Text(), nullable=True),
    sa.Column('damframescore', sa.Float(), nullable=True),
    sa.Column('sireframescore', sa.Float(), nullable=True),
    sa.Column('weanheight', sa.Float(), nullable=True),
    sa.Column('weanweight', sa.Float(), nullable=True),
    sa.Column('weandate', sa.Text(), nullable=True),
    sa.Column('adj205w', sa.Float(), nullable=True),
    sa.Column('adj205h', sa.Float(), nullable=True),
    sa.Column('dob', sa.Text(), nullable=True),
    sa.Column('weanframescore', sa.Float(), nullable=True),
    sa.Column('ageatwean', sa.Float(), nullable=True),
    sa.Column('yearlingweight', sa.Float(), nullable=True),
    sa.Column('yearlingheight', sa.Float(), nullable=True),
    sa.Column('yearlingdate', sa.Text(), nullable=True),
    sa.Column('adjyearlingw', sa.Float(), nullable=True),
    sa.Column('adjyearlingh', sa.Float(), nullable=True),
    sa.Column('yearlingframescore', sa.Float(), nullable=True),
    sa.Column('ageatyearling', sa.Float(), nullable=True),
    sa.Column('customweight', sa.Float(), nullable=True),
    sa.Column('customweightdate', sa.Text(), nullable=True),
    sa.Column('customheight', sa.Float(), nullable=True),
    sa.Column('customheightdate', sa.Text(), nullable=True),
    sa.Column('backfat', sa.Float(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('blockpen', sa.Text(), nullable=True),
    sa.Column('replicate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('master_animal',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('eartag', sa.Text(), nullable=True),
    sa.Column('eid', sa.Text(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('pasturenumber', sa.Text(), nullable=True),
    sa.Column('breed', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('trial', sa.Text(), nullable=True),
    sa.Column('herd', sa.Text(), nullable=True),
    sa.Column('animaltype', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    op.create_table('reproduction',
    sa.Column('cownumber', sa.Integer(), nullable=False),
    sa.Column('breeding', sa.Text(), nullable=True),
    sa.Column('pregnancy', sa.Text(), nullable=True),
    sa.Column('calfatside', sa.Text(), nullable=True),
    sa.Column('totalcalves', sa.Float(), nullable=True),
    sa.Column('previouscalf', sa.Text(), nullable=True),
    sa.Column('currentcalf', sa.Text(), nullable=True),
    sa.Column('damageatbirth', sa.Float(), nullable=True),
    sa.Column('calfsex', sa.Text(), nullable=True),
    sa.Column('calfbirthweight', sa.Float(), nullable=True),
    sa.Column('pasturenumberreproduction', sa.Text(), nullable=True),
    sa.Column('calfdob', sa.Text(), nullable=True),
    sa.Column('damcalvingdisposition', sa.Text(), nullable=True),
    sa.Column('calvingease', sa.Text(), nullable=True),
    sa.Column('udderscore', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('damdispostion', sa.Text(), nullable=True),
    sa.Column('cowframescore', sa.Float(), nullable=True),
    sa.Column('cowwtbreeding', sa.Float(), nullable=True),
    sa.Column('cowhtbreeding', sa.Float(), nullable=True),
    sa.Column('cowwtweaning', sa.Float(), nullable=True),
    sa.Column('cowhtweaning', sa.Float(), nullable=True),
    sa.Column('cowwtcalving', sa.Float(), nullable=True),
    sa.Column('cowhtcalving', sa.Float(), nullable=True),
    sa.Column('bcsweaning', sa.Float(), nullable=True),
    sa.Column('bcscalving', sa.Float(), nullable=True),
    sa.Column('bcsbreeding', sa.Float(), nullable=True),
    sa.Column('customcowwt', sa.Float(), nullable=True),
    sa.Column('customcowht', sa.Float(), nullable=True),
    sa.Column('bulldispostion', sa.Float(), nullable=True),
    sa.Column('bullframescore', sa.Float(), nullable=True),
    sa.Column('bullwtprebreeding', sa.Float(), nullable=True),
    sa.Column('bullhtprebreeding', sa.Float(), nullable=True),
    sa.Column('fertility', sa.Float(), nullable=True),
    sa.Column('mobility', sa.Float(), nullable=True),
    sa.Column('conc', sa.Float(), nullable=True),
    sa.Column('deadabnormal', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cownumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reproduction')
    op.drop_table('master_animal')
    op.drop_table('experiment')
    op.drop_table('animal_inventory')
    op.drop_table('Test1')
    # ### end Alembic commands ###
